### ISSUE TITLE
Obsolete static Makefile

### ISSUE THREAD

**Issue by ssten** [typiconman/m17n-cu#1]
Package's Makefile supports only installation into live filesystem, that is obsolete for many years, but not building a package.
Also, 'install' as first (and default) target confuses and breaks default algorythm.
When using proper (from package) installation, uninstall target in Makefile is not needed.

For minimal, quick and easy solution of this issue I've used the following patch:

files/Makefile.patch 
diff -Naur m17n-cu-master.orig/Makefile m17n-cu-master/Makefile
--- m17n-cu-master.orig/Makefile    2015-03-22 20:39:04.000000000 +0300
+++ m17n-cu-master/Makefile 2016-06-02 11:53:02.000000000 +0300
@@ -1,14 +1,19 @@
-INSTALL = /usr/bin/install -m 644
-DEST = /usr/share/m17n
-ICONDEST = /usr/share/m17n/icons
-LOCALEDEST = /usr/share/i18n/locales
+SHELL = /bin/sh
+DESTDIR ?= /
+INSTALL = /usr/bin/install -m 644 -D
+DEST = $(DESTDIR)usr/share/m17n
+ICONDEST = $(DESTDIR)usr/share/m17n/icons
+LOCALEDEST = $(DESTDIR)/usr/share/i18n/locales

 install:
+  mkdir -p $(DEST)
    $(INSTALL) _.mim $(DEST)
    $(INSTALL) *.lnm $(DEST)
+  mkdir -p $(ICONDEST)
    $(INSTALL) icons/_.png $(ICONDEST)
+  mkdir -p $(LOCALEDEST)
    $(INSTALL) cu_RU $(LOCALEDEST)
-  localedef -f UTF-8 -i cu_RU cu_RU
+  #localedef -f UTF-8 -i cu_RU cu_RU

 uninstall:

Probably, you'll want to perform more advanced improvements.
Consult [upstream docs](https://www.gnu.org/software/make/manual/html_node/index) for that.

**Comment by typiconman** [comment]
Thanks. I'll try to create a real installer for the 1.0 release.

**Comment by typiconman** [comment]
I believe that this is now fixed. @ssten please confirm.

**Comment by ssten** [comment]
Yes, this commit fixes issue.
But, probably it expects corresponding update of INSTALL manual.

**Comment by typiconman** [comment]
I think I've created the necessary files for creating a .deb package, though I'm not sure I've done it 100% correctly.
I've also set up an APT repository here: 
http://www.ponomar.net/apt/
